### ISSUE TITLE
这个仓库主要是做什么？

### ISSUE THREAD

**Issue by wangfenjin** [AngelLiang/tauri-sqlite-vss-demo#1]
有兴趣可以给我发个邮件（可以从我的 profile 页找到），有个想法可以探讨一下

**Comment by AngelLiang** [comment]
在tauri-app框架中使用sqlite-vss向量数据库的示例代码，然后可以使用tauri-app结合sqlite-vss做本地软件开发~
暂时只跑通了macos系统。
